on:
  push:
    branches:
    - main
      
jobs:
  push_to_unions_aoc:
    name: Push changes to Unions AoC
    runs-on: ubuntu-latest
    steps:
    - name: foo
      run: |
        
        mkdir ../tmp
        cd ../tmp
        
        git clone https://github.com/Scrattlebeard/AdventOfCode.git
        cp -rf ../AdventOfCode/* ./AdventOfCode
        cd AdventOfCode
        
        git config user.email "you@example.com"
        git config user.name "Scrattlebeard"
        
        git add *
        git commit -m 'Changes pushed from remote repo'
        git push
        
