on:
  push:
    branches:
    - main

jobs:
  push_to_unions_aoc:
    name: Push changes to Unions AoC
    runs-on: ubuntu-latest
    steps:
    - name: Check out source
      run: |
        mkdir this
        cd this
        git clone https://github.com/Scrattlebeard/AdventOfCode.git

    - name: Get last commit message
      id: commit-message
      run: |
        cd this/AdventOfCode
        echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT

    - name: Check out target
      run: |
        mkdir that
        cd that
        git clone https://github.com/Advent-of-Code-Netcompany-Unions/AoC-2023-DDJ.git

    - name: Copy changes
      run: |          
        cp -rf ./this/AdventOfCode/* ./that/AoC-2023-DDJ/                
        cd that/AoC-2023-DDJ        
        git status

    - name: Git config
      run: |
        cd that/AoC-2023-DDJ        
        git config user.email "you@example.com"
        git config user.name "Scrattlebeard"

    - name: Stage changes
      run: |
        cd that/AoC-2023-DDJ
        git add *        
        git status        
        git restore --staged src/main/kotlin/aoc2015/*
        git restore --staged src/main/kotlin/aoc2021/*
        git restore --staged src/main/kotlin/aoc2022/*        
        git status

    - name: Commit and push
      run: |
        cd that/AoC-2023-DDJ
        git commit -m "${{ steps.commit-message.outputs.message }}"
        git push https://token:${{ secrets.UNIONS_AOC_ACCESS_TOKEN }}@github.com/Advent-of-Code-Netcompany-Unions/AoC-2023-DDJ.git
