on:
  push:
    branches:
    - main
      
jobs:
  push_to_unions_aoc:
    name: Push changes to Unions AoC
    runs-on: ubuntu-latest
    steps:
    - name: Check out source
      run: |
        
        mkdir this
        cd this
        git clone https://github.com/Scrattlebeard/AdventOfCode.git
        
    - name: Check out target
      run: |
      
        mkdir that
        cd that
        git clone https://github.com/Advent-of-Code-Netcompany-Unions/AoC-2022-DDJ.git
        
    - name: Copy changes
      run: |          
        cp -rf ./this/AdventOfCode/* ./that/AoC-2022-DDJ/                
        cd that/AoC-2022-DDJ        
        git status
    
    - name: Git config
      run: |
        cd that/AoC-2022-DDJ        
        git config user.email "you@example.com"
        git config user.name "Scrattlebeard"
    
    - name: Stage changes
      run: |
        cd that/AoC-2022-DDJ
        git add *        
        git status        
        git restore --staged src/aoc2015/*
        git restore --staged src/aoc2021/*        
        git status
    
    - name: Commit and push
      run: |
        cd that/AoC-2022-DDJ
        git commit -m 'Changes pushed from remote repo'
        git push
        
