on:
  push:
    branches:
    - main
      
jobs:
  push_to_unions_aoc:
    name: Push changes to Unions AoC
    runs-on: ubuntu-latest
    steps:
    - name: foo
      run: |
        
        mkdir this
        cd this
        git clone https://github.com/Scrattlebeard/AdventOfCode.git
        
        ls -a
        
        mkdir ../that
        cd ../that
        
        git clone https://github.com/Advent-of-Code-Netcompany-Unions/AoC-2022-DDJ.git
        
        ls -a
        
        git status
        
        cp -rf ../this/* ./
        
        ls -a
        git status
        
        cd AdventOfCode       
        
        git config user.email "you@example.com"
        git config user.name "Scrattlebeard"
        
        git add *
        git commit -m 'Changes pushed from remote repo'
        git push
        
